# Generated by Django 3.2.5 on 2021-08-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_areainfo_aparent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
    ]
