# Generated by Django 3.2.5 on 2022-01-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
    ]
