#coding:gbk
#创建list
place=["Tokyo" , "ChangSha" , "YunNan" , "ShangHai" , "BeiJing"]
print(place)
print("\n")
#用sorted临时按字母排序
print(sorted(place))
print(place)
print("\n")
#用sorted临时反字母排序
print(sorted(place,reverse=True))
print(place)
print("\n")
#用reverse修改排序（反序）
place.reverse()
print(place)
print("\n")
#用reverse修改回排序
place.reverse()
print(place)
print("\n")
#用sort永久修改排序
place.sort()
print(place)
print("\n")
#用sort永久修改排序（反序）
place.sort(reverse=True)
print(place)

